### ISSUE TITLE
How can I use the Quality measure Engine?

### ISSUE THREAD

**Issue by pelagia** [projectcypress/quality-measure-engine#2]
Good afternoon,

Having cloned the library Quality-Measure-Engine: https://github.com/projectcypress/quality-measure-engine , which files or functions I can use to create a very simple example?
Are there functions that are exposed, considering the whole library as a black-box? 

I know that this engine receives JavaScript objects and it runs a map-reduce framework, calculating the results.

What I want to do is a script, providing a file with JavaScript objects, calling the right functions to start the process for the calculation.

I have browsed the code, however I could not figure out what to run and use correclty.

Can anyone from the developers provide me information about that?

I would really appreciate your help.

Kind regards,
Pelagia Sykoudi

**Comment by ssayer** [comment]
Pelagia,

QME is not a black box. It is a Ruby wrapper around the MongoDB MapReduce framework for doing quality measure calculation. Specifically, it wraps Map/Reduce jobs created by https://github.com/projecttacoma/hqmf2js. HQMF2JS (as its name suggests) converts the HQMF into executable javascript.

If you're looking to get started with QME, you should look at MapReduceExecutor which kicks off the Map/Reduce job, or QualityReport which queues the calculation and then tabulates the result.
